name: CI

on:
  push:
    branches:
      - '*'
      - '!master'
    tags:
      - '!refs/tags/*'
  pull_request:
    branches:
      - master

jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: Restore
        run: dotnet restore
      - name: Tests
        run: dotnet test --no-restore -c Release
